services:
  db:
    image: postgres:16
    container_name: seatlock_db
    environment:
      POSTGRES_USER: seatlock
      POSTGRES_PASSWORD: seatlock_pass
      POSTGRES_DB: seatlock
    ports:
      - "5433:5432"
    volumes:
      - seatlock_data:/var/lib/postgresql/data

volumes:
  seatlock_data: